spring:
  config:
    import: optional:application-secret.yml

  datasource:
    url: jdbc:mysql://localhost:3306/order_product_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true